/* Generated by tools/build.py -- do not edit by hand. */
window.BMS_ISSUE_DATA = window.BMS_ISSUE_DATA || {};
window.BMS_ISSUE_DATA["2025-11-autumn"] = {
  "slug": "2025-11-autumn",
  "number": 12,
  "edition": "Autumn 2025",
  "title": "Autumn Newsletter",
  "published": "2025-11-01",
  "dateLabel": "November 2025",
  "summary": "A new madrasah year begins, the autumn prayer timetable takes effect, and our winter warmth appeal opens for the coldest months ahead.",
  "cover": "issues/2025-11-autumn/cover.jpg",
  "tiles": [
    {
      "slug": "imams-message",
      "title": "Message from the Imam",
      "icon": "🕌",
      "blurb": "On gratitude, good neighbours and the coming winter.",
      "photo": "issues/2025-11-autumn/imams-message/photo.jpg",
      "video": "issues/2025-11-autumn/imams-message/video.mp4",
      "textFile": "issues/2025-11-autumn/imams-message/text.md",
      "text": "## On gratitude and good neighbours\n\nAssalamu alaikum wa rahmatullahi wa barakatuh,\n\nAs the clocks go back and the evenings draw in, the masjid becomes the warm\nheart of our week once again. It has been a privilege to see so many of you\nreturn after the summer, and to welcome the new families who have joined us\nfrom across the borough.\n\nThe Prophet صلى الله عليه وسلم told us that\n*\"the best of you are those who are best to their neighbours.\"* This autumn I\nwould like us to take that seriously as a community, not simply as a private\nvirtue.\n\n### Three things we are asking of every household\n\n- **Learn a name.** Our street visit team has knocked on more than 400 doors\n  this year. Ask the volunteers for the names of the neighbours on either side\n  of you and use them.\n- **Share a plate.** The community kitchen runs every Friday after Maghrib.\n  Bring one dish a month and you will feed a neighbour you have never met.\n- **Check in on the elderly.** Forty-two of our members live alone. The\n  befriending rota has room for six more volunteers.\n\nMay Allah accept our efforts, keep our community united, and make this winter\na gentle one for those who feel it most keenly.\n\n**Imam Abdul-Rahman Siddiqui**  \n*Resident Imam, British Muslim Society*"
    },
    {
      "slug": "prayer-timetable",
      "title": "Prayer Timetable",
      "icon": "🕒",
      "blurb": "Autumn timetable, Jumu'ah arrangements and clock changes.",
      "photo": "issues/2025-11-autumn/prayer-timetable/photo.jpg",
      "video": "issues/2025-11-autumn/prayer-timetable/video.mp4",
      "textFile": "issues/2025-11-autumn/prayer-timetable/text.md",
      "text": "## Autumn prayer timetable\n\nThe autumn timetable is now in effect. As the days shorten quickly between\nOctober and December, please check the board in the prayer hall or the masjid\nwebsite each month rather than relying on a printed card from the summer.\n\n### Key changes this month\n\n- **Fajr** moves later each week; the first jama'ah is now 25 minutes after\n  the adhan so that brothers travelling to work can still join.\n- **Isha** is now 7:45 pm at the masjid, with a second jama'ah at 9:00 pm on\n  Fridays and Saturdays for students and shift workers.\n- **Jumu'ah** remains at **1:15 pm** and **2:15 pm**. The second sitting is\n  now the busier of the two — please arrive by 2:00 pm to find a space in\n  the main hall. Overflow seating with a live audio link is available in the\n  annexe.\n\n### A reminder about the clocks\n\nThe clocks go back on **Sunday 26 October**. The timetable printed in the\nOctober leaflet already accounts for this, but please double-check the display\nscreen if you are unsure. Maghrib in particular shifts a full hour.\n\n### Facilities\n\n| Facility | Location | Notes |\n| --- | --- | --- |\n| Wudu area | Ground floor, east wing | Closed for cleaning 30 mins after Isha |\n| Sisters' prayer hall | First floor | Lift access from the main entrance |\n| Children's room | Annexe | Supervised during Jumu'ah |\n\n> If you are new to the masjid, please introduce yourself to one of the\n> stewards in the green lanyards — they will happily show you around."
    },
    {
      "slug": "madrasah",
      "title": "Madrasah & Education",
      "icon": "📚",
      "blurb": "New term, new classes and adult Arabic enrolment.",
      "photo": "issues/2025-11-autumn/madrasah/photo.jpg",
      "video": "issues/2025-11-autumn/madrasah/video.mp4",
      "textFile": "issues/2025-11-autumn/madrasah/text.md",
      "text": "## The new madrasah year begins\n\nAlhamdulillah, we welcomed **184 pupils** back to the madrasah in September,\nour largest intake since the society was founded. Classes run Monday to\nThursday, 5:00 pm to 7:00 pm, with a Friday hifdh circle for pupils who have\ncompleted Juz 30.\n\n### What is new this year\n\n- **Two additional classes** for Years 5 and 6, taught by Ustadha Maryam Khan\n  and Ustadh Bilal Ahmed.\n- **A dedicated girls' class** on Wednesday evenings in the first-floor\n  classroom.\n- **Arabic for adults** returns on Tuesday evenings, 8:00 pm to 9:15 pm.\n  No prior knowledge is assumed.\n\n### Term dates\n\n| Term | Starts | Ends |\n| --- | --- | --- |\n| Autumn | 8 September | 12 December |\n| Half-term break | 27 October | 31 October |\n| Spring | 5 January | 27 March |\n\n### How you can help\n\nWe are still looking for two parent volunteers to help with the book stall and\none qualified teacher for the adult Arabic class. If you can give two hours a\nweek, please speak to the madrasah office or email us.\n\nFees remain **£15 per month** per child, with a family cap of £30 and\na hardship fund available in confidence for any household that needs it. No\nchild has ever been turned away from this madrasah for financial reasons, and\nnone ever will be, insha'Allah."
    },
    {
      "slug": "community-news",
      "title": "Community News",
      "icon": "📰",
      "blurb": "Refurbishment update, new parking rules and the book stall.",
      "photo": "issues/2025-11-autumn/community-news/photo.jpg",
      "video": "issues/2025-11-autumn/community-news/video.mp4",
      "textFile": "issues/2025-11-autumn/community-news/text.md",
      "text": "## Around the community\n\n### Refurbishment reaches the half-way mark\n\nThe wudu facility refurbishment is **60% complete**. The new floor drainage\nis installed, and the accessible cubicle is now in use. The remaining work —\ntiling, new ablution taps and the hand-dryers — is scheduled to finish\nbefore the end of November. Our thanks to the eleven volunteers who gave up\nthree Saturdays to strip out the old fittings.\n\n### Parking on Rutland Road\n\nFollowing complaints from residents, please **do not park on the double yellow\nlines** on Rutland Road before Jumu'ah. The council has agreed to keep the\ncommunity centre car park open on Fridays from 12:30 pm, which gives us\nroughly forty extra spaces. Marshals will be on the gate from 12:45 pm.\n\n### The book stall is back\n\nThe second-hand book stall returns to the foyer every Sunday after Dhuhr.\nDonations of Islamic books, children's readers and dictionaries are very\nwelcome. Proceeds — **£400 last year** — go to the madrasah\nlibrary fund.\n\n### In brief\n\n- The lost property box will be emptied on 30 November. Anything unclaimed\n  goes to the winter shelter.\n- The sisters' halaqah has moved to the first-floor classroom to allow for\n  more attendees.\n- A defibrillator has been installed by the main entrance. Sixteen members\n  have completed training; the next session is on 15 November."
    },
    {
      "slug": "events",
      "title": "Events & Activities",
      "icon": "📅",
      "blurb": "Charity dinner, open day and the winter warmth appeal launch.",
      "photo": "issues/2025-11-autumn/events/photo.jpg",
      "video": "issues/2025-11-autumn/events/video.mp4",
      "textFile": "issues/2025-11-autumn/events/text.md",
      "text": "## What is coming up\n\n### Annual Charity Dinner — Saturday 22 November\n\nOur biggest fundraising evening of the year returns to the community hall.\nDoors open at **6:30 pm** for a 7:00 pm start, with a three-course meal, a\nshort address from the Imam and an auction of promises. Tickets are **£20**\nfor adults and **£10** for under-16s, available from the office after\nevery jama'ah.\n\n### Masjid Open Day — Sunday 7 December, 11:00 am – 4:00 pm\n\nA chance for neighbours, schools and local groups to visit. There will be\nguided tours of the prayer hall, Arabic calligraphy demonstrations, henna,\nand food from our community kitchen. **Please volunteer** — we need\ngreeters, guides and bakers. Email the office to be added to the rota.\n\n### Winter Warmth Appeal launch — from 1 November\n\nSee the Charity & Zakat tile for full details. The appeal launches with a\ncollection after Jumu'ah on 1 November and runs to the end of February.\n\n### Regular gatherings\n\n| Event | When | Where |\n| --- | --- | --- |\n| Community kitchen | Fridays after Maghrib | Annexe |\n| Sisters' halaqah | Tuesdays, 11:00 am | First floor |\n| Youth halaqah (13–18) | Saturdays, 6:30 pm | Annexe |\n| New Muslims circle | First Sunday, 2:00 pm | Meeting room |"
    },
    {
      "slug": "youth-corner",
      "title": "Youth Corner",
      "icon": "⚽",
      "blurb": "Indoor league, mentoring scheme and exam support.",
      "photo": "issues/2025-11-autumn/youth-corner/photo.jpg",
      "video": "issues/2025-11-autumn/youth-corner/video.mp4",
      "textFile": "issues/2025-11-autumn/youth-corner/text.md",
      "text": "## Youth news\n\n### Indoor football league kicks off\n\nThe winter indoor league starts on **9 November** at the leisure centre on\nMill Lane. Eight teams, twelve weeks, £3 per player per week. Ages 13–18.\nSign-up sheets are on the noticeboard, and we need two more parent referees.\n\n### Mentoring scheme needs mentors\n\nOur mentoring scheme pairs GCSE and A-level students with professionals from\nthe community for one hour a month. Twenty-two young people are waiting for a\nmentor. If you work in medicine, engineering, law, IT, teaching or the trades\nand can spare an hour a month, please get in touch — it makes an enormous\ndifference.\n\n### Exam support sessions\n\nFree study sessions run every Saturday from 4:00 pm in the annexe during the\nrun-up to mock exams, with a quiet room, past papers, and volunteers on hand\nfor maths and science.\n\n### Youth committee\n\nThe youth committee meets on the first Friday of each month after Isha.\nEveryone aged 13–18 is welcome, and new ideas are always considered —\nlast year's committee organised the summer camp, the charity football match\nand the Eid funfair."
    },
    {
      "slug": "sisters-corner",
      "title": "Sisters' Corner",
      "icon": "🌸",
      "blurb": "New halaqah times, fitness class and a babysitting rota.",
      "photo": "issues/2025-11-autumn/sisters-corner/photo.jpg",
      "video": "issues/2025-11-autumn/sisters-corner/video.mp4",
      "textFile": "issues/2025-11-autumn/sisters-corner/text.md",
      "text": "## Sisters' corner\n\n### The halaqah has moved — and grown\n\nThe Tuesday morning halaqah now meets in the **first-floor classroom** at\n11:00 am, which gives us room for forty instead of eighteen. We are studying\nthe names and attributes of Allah, one name a week, with plenty of time for\ndiscussion. Tea and something sweet afterwards, always.\n\n### Women-only fitness, Wednesdays 7:30 pm\n\nA new women-only fitness class has started in the community hall. All\nabilities, no experience needed, £4 per session. Please bring a mat if\nyou have one; we have ten spare.\n\n### Babysitting rota\n\nSo that more sisters can attend classes and gatherings, we are setting up a\nvolunteer babysitting rota in the children's room during Tuesday halaqah and\nWednesday fitness. If you would like to help for one session a month — or\nif you need the service — please add your name to the sheet in the foyer.\n\n### Sisters' social\n\nThe next sisters' social is a **bring-and-share brunch** on Saturday 30\nNovember at 10:30 am. No need to book, just come. It is a relaxed morning and\na good place to meet other sisters if you are new to the area.\n\n> \"The believing men and believing women are allies of one another.\"\n> — Surah at-Tawbah 9:71"
    },
    {
      "slug": "charity-zakat",
      "title": "Charity & Zakat",
      "icon": "💝",
      "blurb": "Winter warmth appeal, food bank figures and zakat clinic dates.",
      "photo": "issues/2025-11-autumn/charity-zakat/photo.jpg",
      "video": "issues/2025-11-autumn/charity-zakat/video.mp4",
      "textFile": "issues/2025-11-autumn/charity-zakat/text.md",
      "text": "## Winter warmth appeal\n\nFrom **1 November** to the end of February we are collecting for the winter\nwarmth appeal. Last year the community raised **£18,400**, which funded\n180 winter packs, four hundred hot meals and emergency heating grants for\neleven local households.\n\n### What we need\n\n- **Coats, blankets and sleeping bags** — clean and in good condition.\n  Drop them in the labelled crates in the foyer.\n- **Non-perishable food** — rice, lentils, tinned tomatoes, oil, tea.\n- **Money** — every pound is spent locally. Gift Aid forms are available\n  at the office and add 25% at no cost to you.\n\n### Food bank update\n\nThe community food bank distributed **1,240 parcels** in the last twelve\nmonths, up 18% on the year before. Sixty volunteers keep it running. Demand\npeaks in January, so please keep the crates filled through the winter.\n\n### Zakat clinic\n\nOur zakat clinic runs on the **first and third Sunday** of each month from\n1:00 pm to 3:00 pm. Volunteers can help you calculate your zakat, explain the\nnisab thresholds and, if you wish, distribute it directly through the\nsociety's verified channels. All conversations are confidential.\n\n### Where your money went last quarter\n\n| Cause | Amount |\n| --- | --- |\n| Local hardship grants | £4,120 |\n| Food bank running costs | £2,300 |\n| Winter packs | £1,850 |\n| Overseas emergency relief | £3,000 |"
    },
    {
      "slug": "health-wellbeing",
      "title": "Health & Wellbeing",
      "icon": "❤️",
      "blurb": "Flu clinic, blood pressure checks and mental health support.",
      "photo": "issues/2025-11-autumn/health-wellbeing/photo.jpg",
      "video": "issues/2025-11-autumn/health-wellbeing/video.mp4",
      "textFile": "issues/2025-11-autumn/health-wellbeing/text.md",
      "text": "## Looking after ourselves\n\n### Free flu clinic at the masjid\n\nThe NHS mobile vaccination team will be with us on **Sunday 16 November**,\n10:00 am to 2:00 pm, in the annexe. The clinic is free and open to everyone\neligible, and the team is experienced at providing a culturally sensitive\nservice. Walk in, no appointment needed.\n\n### Blood pressure checks\n\nVolunteer nurses run drop-in blood pressure and blood sugar checks after\nJumu'ah on the last Friday of each month. It takes four minutes and it has\nalready flagged eleven people for follow-up with their GP.\n\n### Mental health and wellbeing\n\nThe wellbeing circle meets on the second Sunday of the month at 3:00 pm. It\nis a confidential, facilitated space to talk about stress, grief, anxiety and\nthe pressures of work and family life. Everything shared stays in the room.\n\nIf you or someone you know is struggling, please speak to the Imam or any\nmember of the wellbeing team. Our faith teaches us to seek help, not to\nsuffer in silence.\n\n### Staying well this winter\n\n- Get the flu jab if you are eligible.\n- Keep moving — even a twenty-minute walk after Maghrib counts.\n- Check on elderly neighbours during cold snaps.\n- The masjid is a **warm welcome space** this winter: open 10:00 am to\n  4:00 pm daily, warm, with tea and company."
    }
  ]
};
