/* Generated by tools/build.py -- do not edit by hand. */
window.BMS_ISSUE_DATA = window.BMS_ISSUE_DATA || {};
window.BMS_ISSUE_DATA["2025-08-summer"] = {
  "slug": "2025-08-summer",
  "number": 11,
  "edition": "Summer 2025",
  "title": "Summer Newsletter",
  "published": "2025-08-01",
  "dateLabel": "August 2025",
  "summary": "Eid al-Adha, the Hajj report, a record-breaking summer fete and our young people's camp in the Peak District.",
  "cover": "issues/2025-08-summer/cover.jpg",
  "tiles": [
    {
      "slug": "eid-al-adha",
      "title": "Eid al-Adha",
      "icon": "🕋",
      "blurb": "Three jama'ahs, 900 worshippers and the qurbani total.",
      "photo": "issues/2025-08-summer/eid-al-adha/photo.jpg",
      "video": "issues/2025-08-summer/eid-al-adha/video.mp4",
      "textFile": "issues/2025-08-summer/eid-al-adha/text.md",
      "text": "## Eid al-Adha 2025\n\nAlhamdulillah, Eid al-Adha this year brought **over 900 worshippers** through\nour doors across three jama'ahs, the largest Eid gathering in the society's\nhistory.\n\n### The day in numbers\n\n| | |\n| --- | --- |\n| Worshippers | 913 |\n| Prayers held | 3 (7:00, 8:30, 10:00 am) |\n| Qurbani shares arranged | 62 |\n| Children at the funfair | 240 |\n\n### Qurbani\n\nSixty-two shares were arranged through the society, distributing meat to\nfamilies locally and to partners overseas in Gaza, Sudan and Bangladesh. The\ncost per share was £65; the committee agreed to subsidise eleven shares\nfor households in hardship, funded from the general welfare fund.\n\n### Thank you\n\nEid does not happen by itself. Thank you to the forty volunteers who arrived\nat 6:00 am to lay out the halls, the sisters' team who ran the children's\nactivities, the traffic marshals, and everyone who brought food for the\nshared breakfast — there was enough to send plates to the sheltered\nhousing on Oakfield Road."
    },
    {
      "slug": "hajj-report",
      "title": "Hajj Report",
      "icon": "🕋",
      "blurb": "Fourteen of our members completed the pilgrimage.",
      "photo": "issues/2025-08-summer/hajj-report/photo.jpg",
      "video": "issues/2025-08-summer/hajj-report/video.mp4",
      "textFile": "issues/2025-08-summer/hajj-report/text.md",
      "text": "## Fourteen pilgrims return\n\nFourteen members of the society performed Hajj this year, including three\nmarried couples and, for the first time, two of our youth volunteers who\ntravelled with a supervised group. All returned safely, alhamdulillah.\n\n### Their reflections\n\n> \"The thing nobody tells you is how ordinary everyone is. You are standing\n> shoulder to shoulder with a hundred different nationalities and there is no\n> rank at all. I have never felt so small or so much a part of something.\"\n> — Brother Yusuf, first Hajj\n\n> \"I prepared for the heat and the walking. I did not prepare for how much I\n> would miss the group when it was over.\"\n> — Sister Aisha, first Hajj\n\n### A Hajj preparation course\n\nGiven the interest, we will run a **Hajj and Umrah preparation course** over\nfour evenings in the autumn, covering the rites, practical logistics, health\nand the spiritual dimensions of the journey. Register your interest at the\noffice; the course is open to anyone intending to travel in the next two\nyears.\n\nMay Allah accept the pilgrimage of all who went, and grant the same\nopportunity to those who long for it."
    },
    {
      "slug": "summer-fete",
      "title": "Summer Fete",
      "icon": "🎉",
      "blurb": "A record £7,200 raised on the sunniest day of the year.",
      "photo": "issues/2025-08-summer/summer-fete/photo.jpg",
      "video": "issues/2025-08-summer/summer-fete/video.mp4",
      "textFile": "issues/2025-08-summer/summer-fete/text.md",
      "text": "## The summer fete raises a record £7,200\n\nThe sun stayed out for the whole of the summer fete and so did the community.\nWe welcomed an estimated **1,100 visitors** to the field behind the community\ncentre — our biggest turnout yet.\n\n### What made it work\n\n- **Food from fourteen countries**, cooked by families from across the\n  society. The biryani sold out in ninety minutes.\n- **The children's zone**, run by the youth committee, with a bouncy castle,\n  face painting and a sponge-the-imam stall that raised £800 on its own.\n- **The bazaar**, with 22 stalls from local Muslim businesses.\n- **The car boot sale**, which brought in neighbours who had never set foot\n  in the masjid before.\n\n### Where the money goes\n\nThe £7,200 raised is split between the masjid refurbishment fund\n(£4,000), the madrasah library (£1,700) and the youth camp subsidy\n(£1,500).\n\nThank you to the 63 volunteers and the local businesses who donated prizes,\nwater and ice cream. Planning for next year starts in January — new\nhelpers are very welcome."
    },
    {
      "slug": "youth-camp",
      "title": "Youth Summer Camp",
      "icon": "⛺",
      "blurb": "Three days in the Peak District for 38 young people.",
      "photo": "issues/2025-08-summer/youth-camp/photo.jpg",
      "video": "issues/2025-08-summer/youth-camp/video.mp4",
      "textFile": "issues/2025-08-summer/youth-camp/text.md",
      "text": "## Three days in the Peak District\n\nThirty-eight young people aged 12–17 spent three days at a campsite near\nBakewell in July, accompanied by eight adult volunteers and two qualified\nfirst-aiders.\n\n### What they got up to\n\n- A seven-mile hike across the moor (completed by everyone, with only\n  moderate complaining)\n- Night-time astronomy, made memorable by a clear sky and no light pollution\n- A workshop on leadership and teamwork led by two of our older youth\n  volunteers\n- Fajr in the open air, which several of the young people said was the\n  highlight of the trip\n\n### Feedback from the group\n\n> \"I came not knowing anybody. By the second night I had about fifteen\n> friends. I did not want to go home.\"\n> — Participant, age 14\n\n### Next year\n\nThe camp is heavily subsidised — families paid £35 towards a real\ncost of about £140 per head, with the difference met by the fete and by\na donation from a member. If you would like to sponsor a place next year,\nplease contact the youth team."
    },
    {
      "slug": "madrasah-graduation",
      "title": "Madrasah Graduation",
      "icon": "🎓",
      "blurb": "Eleven pupils complete their hifdh of Juz 30.",
      "photo": "issues/2025-08-summer/madrasah-graduation/photo.jpg",
      "video": "issues/2025-08-summer/madrasah-graduation/video.mp4",
      "textFile": "issues/2025-08-summer/madrasah-graduation/text.md",
      "text": "## Graduation ceremony 2025\n\nEleven pupils completed their hifdh of **Juz 30** this year, and four\ncompleted the full Qur'an recitation with tajweed certification. The\ngraduation ceremony was held in the community hall in front of around three\nhundred family members and friends.\n\n### The graduates\n\nEach pupil recited a passage they had chosen themselves. The standard this\nyear was exceptional, and the examiners commented on the confidence of the\nyounger pupils in particular.\n\n### Prize winners\n\n| Award | Pupil |\n| --- | --- |\n| Best overall progress | Sumayya H. |\n| Best tajweed | Ibrahim A. |\n| Most improved | Zakariya M. |\n| Service to the madrasah | Hafsa R. |\n\n### Looking ahead\n\nThe madrasah grows every year and we need more teaching capacity. If you are\na fluent reader with a good grasp of tajweed and two hours a week to spare,\nplease speak to the madrasah office. Training and support are provided, and\nall teaching is done in pairs."
    },
    {
      "slug": "sports",
      "title": "Sports",
      "icon": "🏆",
      "blurb": "Cricket season review and the inter-masjid football cup.",
      "photo": "issues/2025-08-summer/sports/photo.jpg",
      "video": "issues/2025-08-summer/sports/video.mp4",
      "textFile": "issues/2025-08-summer/sports/text.md",
      "text": "## Summer of sport\n\n### Cricket\n\nThe BMS cricket team finished the season **third in the league**, our best\nresult yet, with six wins, three losses and one washout. Top scorer was\nBrother Hamza with 412 runs; bowler of the season was Brother Idris with 19\nwickets.\n\nMore importantly, the team ran four Sunday morning coaching sessions for\nunder-12s, with 55 children attending across the summer.\n\n### Football\n\nThe inter-masjid five-a-side cup was hosted at Mill Lane in June. Eight\nmasjids took part and we reached the semi-final, losing narrowly to the\neventual winners. The atmosphere was superb and the trophy will be back in\nthe borough next year.\n\n### Coming up\n\nAutumn indoor sessions begin in September for ages 13–18, and a walking\nfootball group for the over-50s is being considered — register your\ninterest at the office if you would like to join."
    },
    {
      "slug": "volunteers",
      "title": "Volunteer Spotlight",
      "icon": "🤝",
      "blurb": "Meet the people who keep the society running.",
      "photo": "issues/2025-08-summer/volunteers/photo.jpg",
      "video": "issues/2025-08-summer/volunteers/video.mp4",
      "textFile": "issues/2025-08-summer/volunteers/text.md",
      "text": "## Volunteer spotlight\n\nThe society runs on volunteers. This issue we say thank you to three of them.\n\n### Sister Nasreen — community kitchen\n\nNasreen has cooked at the Friday community kitchen for nine years, and rarely\nmisses a week.\n\n> \"I started because I had just retired and I was bored. Now I have about\n> forty friends I would never otherwise have met. I get far more out of it\n> than I put in.\"\n\n### Brother Tariq — maintenance\n\nTariq, a retired electrician, has rewired half the building, fixed the\nboiler twice, and is currently leading the wudu refurbishment.\n\n> \"If you can hold a screwdriver, you can help. The trick is to turn up.\"\n\n### Sister Hina — safeguarding and youth\n\nHina leads safeguarding for all our youth activities and has trained eleven\nother volunteers.\n\n> \"It is not glamorous work. But parents need to know that when they leave\n> their children with us, nothing matters more to us than their safety.\"\n\n### Join them\n\nWe currently need: two parent volunteers for the madrasah book stall, six\nbefrienders for elderly members, two referees for the youth league, and a\ntreasurer's assistant. Two hours a month is genuinely enough."
    }
  ]
};
