/* Generated by tools/build.py -- do not edit by hand. */
window.BMS_ISSUE_DATA = window.BMS_ISSUE_DATA || {};
window.BMS_ISSUE_DATA["2026-09-autumn"] = {
  "slug": "2026-09-autumn",
  "number": 13,
  "edition": "Autumn 2026",
  "title": "Autumn Newsletter",
  "published": "2026-09-15",
  "dateLabel": "September 2026",
  "summary": "Placeholder issue, set up and ready for the real Autumn 2026 articles — replace this summary and the tile below.",
  "cover": "issues/2026-09-autumn/cover.jpg",
  "tiles": [
    {
      "slug": "new-article",
      "title": "New Article",
      "icon": "📝",
      "blurb": "Placeholder tile, ready for the real article.",
      "photo": "issues/2026-09-autumn/new-article/photo.jpg",
      "video": "issues/2026-09-autumn/new-article/video.mp4",
      "textFile": "issues/2026-09-autumn/new-article/text.md",
      "text": "## This tile is ready for a real article\n\nThis issue and this tile were generated as a starting point, so the folder\nstructure is already in place and publishing works end to end. Nothing here\nis real news yet — replace it whenever you are ready.\n\n### Putting the real article in\n\n1. Open `tools/content.py` and edit the `text` of the `new-article` tile in\n   the `2026-09-autumn` issue. It is ordinary Markdown: `##` headings,\n   `-` bullets, `>` pull quotes and pipe tables all work.\n2. Replace `issues/2026-09-autumn/new-article/photo.jpg` with the real\n   photograph, and `video.mp4` with the real clip (H.264 `.mp4`).\n3. Run `python3 tools/build.py`, then commit and push.\n\nThe build only creates media that is missing, so a real photograph dropped\ninto a tile folder is never overwritten.\n\n### Adding more tiles\n\nGive each tile a `slug`, a `title`, an `icon` and a `blurb` in\n`tools/content.py`, and `tools/build.py` creates its folder complete with a\nphoto, a video and a text file."
    }
  ]
};
