/* Generated by tools/build.py -- do not edit by hand. */
window.BMS_ISSUES = [
  {
    "slug": "2026-09-autumn",
    "number": 13,
    "edition": "Autumn 2026",
    "title": "Autumn Newsletter",
    "published": "2026-09-15",
    "dateLabel": "September 2026",
    "summary": "Placeholder issue, set up and ready for the real Autumn 2026 articles — replace this summary and the tile below.",
    "cover": "issues/2026-09-autumn/cover.jpg",
    "tileCount": 1
  },
  {
    "slug": "2025-11-autumn",
    "number": 12,
    "edition": "Autumn 2025",
    "title": "Autumn Newsletter",
    "published": "2025-11-01",
    "dateLabel": "November 2025",
    "summary": "A new madrasah year begins, the autumn prayer timetable takes effect, and our winter warmth appeal opens for the coldest months ahead.",
    "cover": "issues/2025-11-autumn/cover.jpg",
    "tileCount": 9
  },
  {
    "slug": "2025-08-summer",
    "number": 11,
    "edition": "Summer 2025",
    "title": "Summer Newsletter",
    "published": "2025-08-01",
    "dateLabel": "August 2025",
    "summary": "Eid al-Adha, the Hajj report, a record-breaking summer fete and our young people's camp in the Peak District.",
    "cover": "issues/2025-08-summer/cover.jpg",
    "tileCount": 7
  },
  {
    "slug": "2025-03-ramadan",
    "number": 10,
    "edition": "Ramadan 2025",
    "title": "Ramadan Newsletter",
    "published": "2025-03-01",
    "dateLabel": "March 2025",
    "summary": "Welcoming Ramadan: taraweeh arrangements, the community iftar rota, zakat guidance and Eid al-Fitr planning.",
    "cover": "issues/2025-03-ramadan/cover.jpg",
    "tileCount": 7
  }
];
