/* Generated by tools/build.py -- do not edit by hand. */
window.BMS_ISSUE_DATA = window.BMS_ISSUE_DATA || {};
window.BMS_ISSUE_DATA["2025-03-ramadan"] = {
  "slug": "2025-03-ramadan",
  "number": 10,
  "edition": "Ramadan 2025",
  "title": "Ramadan Newsletter",
  "published": "2025-03-01",
  "dateLabel": "March 2025",
  "summary": "Welcoming Ramadan: taraweeh arrangements, the community iftar rota, zakat guidance and Eid al-Fitr planning.",
  "cover": "issues/2025-03-ramadan/cover.jpg",
  "tiles": [
    {
      "slug": "welcome-ramadan",
      "title": "Welcome Ramadan",
      "icon": "🌙",
      "blurb": "The blessed month arrives — and the masjid is ready.",
      "photo": "issues/2025-03-ramadan/welcome-ramadan/photo.jpg",
      "video": "issues/2025-03-ramadan/welcome-ramadan/video.mp4",
      "textFile": "issues/2025-03-ramadan/welcome-ramadan/text.md",
      "text": "## Welcome to Ramadan\n\nBismillah. The blessed month is upon us once again, and the masjid has been\nprepared for it: the halls cleaned and carpeted, the kitchen stocked, the\ntimetables printed, and the taraweeh rota filled.\n\n### Our intention for this month\n\nThis year the committee has chosen a single theme for Ramadan: **the\nneighbour**. Every Friday reminder, every children's activity and every iftar\ninvitation will return to it. Our neighbours — Muslim and non-Muslim\nalike — see more of us in Ramadan than in any other month. Let them see\npatience, generosity and good humour.\n\n### Practical arrangements\n\n- **Suhoor** packs are available from the office for anyone fasting alone.\n- The masjid will be open from **one hour before Fajr** through to 11:00 pm.\n- The **community kitchen** serves iftar every single evening. Please book\n  for the weekends, which fill up quickly.\n- **I'tikaf** in the last ten nights is by registration only; twelve places\n  are available.\n\n### A du'a for the month\n\n> \"O Allah, bless us in Rajab and Sha'ban, and let us reach Ramadan.\""
    },
    {
      "slug": "taraweeh",
      "title": "Taraweeh & Prayer",
      "icon": "🕌",
      "blurb": "Eight or twenty rak'ahs, timings and the youth night.",
      "photo": "issues/2025-03-ramadan/taraweeh/photo.jpg",
      "video": "issues/2025-03-ramadan/taraweeh/video.mp4",
      "textFile": "issues/2025-03-ramadan/taraweeh/text.md",
      "text": "## Taraweeh and the night prayers\n\nTaraweeh begins on the first night of Ramadan after Isha, at approximately\n**8:20 pm**, and finishes around 9:45 pm.\n\n### The schedule\n\n| Prayer | Time | Hall |\n| --- | --- | --- |\n| Isha | 8:20 pm | Main hall |\n| Taraweeh (8 rak'ahs) | 8:35 pm | Main hall |\n| Taraweeh (20 rak'ahs) | 8:35 pm | Annexe |\n| Tahajjud (last 10 nights) | 2:30 am | Main hall |\n\nWe offer both eight and twenty rak'ahs, in separate halls, so that everyone\ncan pray as they are accustomed. The recitation in the main hall completes\none juz each night, finishing the Qur'an on the twenty-ninth night.\n\n### Youth taraweeh night\n\nEvery Saturday, the youth committee leads the first four rak'ahs with two of\nour older madrasah pupils reciting. It has become one of the highlights of\nthe month and the main hall is always full.\n\n### Practical notes\n\n- Please **park considerately** — taraweeh finishes late and residents\n  need access to their drives.\n- The sisters' hall is open for every prayer, with a live audio and video\n  link from the main hall.\n- Wheelchair spaces and chairs are available at the front of both halls."
    },
    {
      "slug": "community-iftar",
      "title": "Community Iftar",
      "icon": "🍽️",
      "blurb": "Thirty nights, thirty families, and how to host one.",
      "photo": "issues/2025-03-ramadan/community-iftar/photo.jpg",
      "video": "issues/2025-03-ramadan/community-iftar/video.mp4",
      "textFile": "issues/2025-03-ramadan/community-iftar/text.md",
      "text": "## The community iftar\n\nFor the whole of Ramadan, the community kitchen serves a free iftar every\nevening. Last year we served **6,400 meals** across the month. It takes\nroughly thirty families and a small army of volunteers to make it happen.\n\n### Hosting a night\n\nIf you would like to sponsor an evening, you can do it in three ways:\n\n- **Cook** — provide the main dish for around 120 people.\n- **Contribute** — £150 covers the ingredients for a full evening.\n- **Serve** — join the cleaning and serving rota, one evening a week.\n\nThe rota is on the noticeboard and is filling fast. Weekend nights go first,\nso if you have a preference, sign up early.\n\n### The neighbours' night\n\nOn **Friday 21 March** we are holding a special iftar for our non-Muslim\nneighbours, with an open invitation delivered to 300 houses on the surrounding\nstreets. Last year 74 neighbours came. Please make them welcome — sit\nwith someone you do not know and answer their questions warmly.\n\n### Menu\n\n| Day | Main |\n| --- | --- |\n| Monday | Chicken biryani |\n| Tuesday | Lamb pilau |\n| Wednesday | Daal and vegetable curry |\n| Thursday | Chicken curry and rice |\n| Friday | Fish curry |\n| Saturday | Community pot luck |\n| Sunday | Soup, samosas and pakoras |"
    },
    {
      "slug": "zakat-sadaqah",
      "title": "Zakat & Sadaqah",
      "icon": "💰",
      "blurb": "Calculating your zakat and where the society distributes it.",
      "photo": "issues/2025-03-ramadan/zakat-sadaqah/photo.jpg",
      "video": "issues/2025-03-ramadan/zakat-sadaqah/video.mp4",
      "textFile": "issues/2025-03-ramadan/zakat-sadaqah/text.md",
      "text": "## Zakat and sadaqah in Ramadan\n\nThe reward for generosity is multiplied in this month, and the society's\nzakat fund is the simplest way to make sure your zakat reaches those who need\nit locally.\n\n### Do you need to pay zakat?\n\nZakat is due on wealth above the **nisab** threshold — roughly the value\nof 87.48 grams of gold — held for a full lunar year. If you are unsure,\nour volunteers will help you work it out. Bring a rough list of your savings,\ngold, shares and any money owed to you, and a list of your debts.\n\n### Zakat clinic dates\n\nSundays **9 March** and **23 March**, 1:00 pm to 3:00 pm in the meeting room.\nNo appointment needed. All conversations are private.\n\n### Where last year's zakat went\n\n| Category | Share |\n| --- | --- |\n| Local families in hardship | 46% |\n| Orphans and widows (overseas) | 22% |\n| Emergency relief | 18% |\n| Water and sanitation projects | 9% |\n| Education and madrasah places | 5% |\n\n### Sadaqah\n\nZakat is an obligation; sadaqah is open-ended. The fidyah and kaffarah rate\nthis year is **£5 per day**. If you would like to feed a fasting person\nfor the month, £150 covers a full iftar for the community."
    },
    {
      "slug": "childrens-corner",
      "title": "Children's Corner",
      "icon": "🌟",
      "blurb": "Ramadan calendars, a colouring competition and the fun day.",
      "photo": "issues/2025-03-ramadan/childrens-corner/photo.jpg",
      "video": "issues/2025-03-ramadan/childrens-corner/video.mp4",
      "textFile": "issues/2025-03-ramadan/childrens-corner/text.md",
      "text": "## Children's corner\n\nRamadan is a month children remember for the rest of their lives. Here is how\nwe are making it special for the youngest members of the society.\n\n### Ramadan calendars\n\nFree wall calendars are available in the foyer for every child. Each day has a\ngood deed to tick off — help with the washing up, call a grandparent,\nshare a toy — alongside the fasting and prayer trackers. Completed\ncalendars go into a prize draw on Eid.\n\n### Colouring competition\n\nEntries for the Ramadan colouring competition are now open, in three age\ngroups: under 6, 7–10 and 11–14. Sheets are at the back of the hall\nand prizes will be awarded at the Eid fun day.\n\n### Children's iftar\n\nA shorter children's iftar runs in the annexe every Saturday at 6:15 pm,\nwith food children actually want to eat, a short story, and a craft activity.\nParents are welcome to stay.\n\n### Family fun day — Saturday 29 March\n\nBouncy castle, henna, a treasure hunt, a lantern-making workshop and the\never-popular sponge the imam. 2:00 pm to 5:00 pm, free entry, bring the\nwhole family.\n\n### A note for parents\n\nPlease do not pressure young children to fast before they are ready. Let them\npractise half-days, keep it joyful, and let the masjid be somewhere they want\nto be."
    },
    {
      "slug": "new-muslims",
      "title": "New Muslims",
      "icon": "🌱",
      "blurb": "Six shahadahs, a warm welcome and the revert support circle.",
      "photo": "issues/2025-03-ramadan/new-muslims/photo.jpg",
      "video": "issues/2025-03-ramadan/new-muslims/video.mp4",
      "textFile": "issues/2025-03-ramadan/new-muslims/text.md",
      "text": "## New Muslims and reverts\n\n**Six people took their shahadah** with the society since the last\nnewsletter. Each one is a gift to our community, and each one needs more than\na certificate and a handshake.\n\n### The support circle\n\nThe new Muslims circle meets on the **first Sunday of the month at 2:00 pm**\nin the meeting room. It is led by reverts, for reverts — covering the\npracticalities of prayer, fasting and everyday life alongside the bigger\nquestions of faith, family and identity.\n\n### Buddy scheme\n\nEvery new Muslim is offered a buddy: a member of the society who checks in\nweekly for the first six months, answers questions without judgement, and\nhelps navigate everything from halal shopping to telling your family.\n\nWe currently need **four more buddies**. Training and materials are provided.\nIf you have been Muslim for more than two years, you are qualified — the\nonly real requirement is patience and warmth.\n\n### Ramadan for a new Muslim\n\nFasting your first Ramadan can feel daunting. Please speak to the Imam about\nany concessions, health concerns or work arrangements, and let us support\nyou. There is no expectation of perfection, only of sincerity."
    },
    {
      "slug": "eid-preparations",
      "title": "Eid al-Fitr",
      "icon": "🎉",
      "blurb": "Three jama'ahs, zakat al-fitr and the Eid fun day.",
      "photo": "issues/2025-03-ramadan/eid-preparations/photo.jpg",
      "video": "issues/2025-03-ramadan/eid-preparations/video.mp4",
      "textFile": "issues/2025-03-ramadan/eid-preparations/text.md",
      "text": "## Preparing for Eid al-Fitr\n\nEid al-Fitr is expected on **Sunday 30 March**, subject to the sighting of the\nmoon. Confirmation will be announced on the society's website and by text\nmessage to everyone on the mailing list.\n\n### Prayer arrangements\n\n| Jama'ah | Time | Hall |\n| --- | --- | --- |\n| First | 7:00 am | Main hall |\n| Second | 8:30 am | Main hall |\n| Third | 10:00 am | Main hall and annexe |\n\nPlease arrive early and, if possible, walk. There will be no parking on\nRutland Road and marshals will direct traffic from 6:30 am.\n\n### Zakat al-Fitr\n\nZakat al-Fitr is **£7 per person** this year and must reach those\nentitled to it **before the Eid prayer**. Please pay at the office or online\nby the evening of 29 March at the latest. This is a separate obligation from\nzakat on wealth.\n\n### Eid fun day\n\nStraight after the third jama'ah: the Eid fun day on the field. Rides, stalls,\nfood, sports and the children's prize-giving. Free entry; bring a dish for\nthe shared table if you can.\n\n### Sunan of Eid\n\n- Take a bath and wear your best clothes.\n- Eat something before leaving for the prayer.\n- Say the takbir on the way.\n- Change your route home.\n- And forgive somebody. It is the best thing you can do on Eid."
    }
  ]
};
